package models;

public enum Request {
	USER_NAME,CLOSE_CONNECTION,WRONG_INFO, CREATE_ACCOUNT, START_PROGRAM_EMPLOYEE, START_PROGRAM_COMPANY, DEPARTMENT_LIST, CITY_LIST, SEND_INFO_EMPLOYEE_ACCOUNT, SEND_INFO_COMPANY_ACCOUNT
}
