package controller;

public enum Events {
	SING_IN, SING_UP, COME_BACK_CREATE, CHANGE_TO_SING_UP, CLOSE_APP, QUESTION_PANEL, SAVE_QUESTIONS, 
	WAITING_OPPONENT, PLAY_ONE_VS_ONE, WAITING_OPPONENT_CANCEL
}
