package connection;

public enum Request {
	CREATE_ACCOUNT_USER, EMAIL_OK_NICKNAME_OK, EMAIL_BAD_NICKNAME_OK, EMAIL_OK_NICKNAME_BAD, EMAIL_BAD_NICKNAME_BAD,
	USER_CREATED_CORRECTLY, START_PROGRAM, LOG_IN, LOGING_FAIL, LOGING_ACCEPTED, CLOSE_CONNECTION, SEND_INFO_USER_AFTER_LOGIN
	, CHANGE_QUESTION_LIST, PLAY_ONE_VS_ONE, START_GAME_ONE_VS_ONE, SEND_QUESTIONS_GAME_ONE_VS_ONE,
	CHANGE_QUESTION_ONE_VS_ONE, SET_NEXT_QUESTION_ONE_VS_ONE, OPPONENT_ANSWERED, GAME_FINISH_ONE_VS_ONE,
	SEND_RESULTS_GAME_ONE_VS_ONE, RELOAD_INFO_USER, CANCEL_WAIT_OPPONENT_ONE_VS_ONE
}
